#! /bin/bash

echo Generating dataset  #"Usage: ds sl qs d_dx d_dy d_dist q_dx q_dy q_dist" 



export dpostfix="${ds}_${dx}_${dy}_${d_dist}"
export qpostfix="${qs}_${qx}_${qy}_${q_dist}"


export datafile="data${dpostfix}"
export queryfile="query${qpostfix}"

#time ../../test-rtree-Generator $ds $sl $qs $dx $dy $d_dist $qx $qy $q_dist > d

time ../../test-rtree-Generator 1 0 $qs 0.1 0.1 f $qx $qy $q_dist > d   # 1 0 0.1 0.1 f is dummy



# generate only queries..
awk '{if ($1 == 2) print $0}' < d > $queryfile      
rm -rf d

awk 'BEGIN {}
{print $3," ",$4; print $5," ",$4; print $5," ",$6; }  # may combine the prints in the same line if you wish.
{print $3," ",$6; print $3," ",$4; print ""}
END{}' $queryfile > "pltquery"

mkdir -p plt   # -p flag: mk dir only if dir does not exist.
mv "pltquery" ./plt

# you may plot data and query with the following command:
# gnuplot> plot "pltdata" using 1:2 w l, "pltquery" using 1:2 with lines lw 4