#! /bin/bash

# ---> SET QUERY SET characteristics:
export qs=100
export qx=0.01
export qy=0.01
export q_dist=f

# CHANGE THE FOLLWING ONLY IF NEW INDEX İS LOADED..
# DO NOT TOUCH FOLLOWING !!! use the following already exist "data" characteristics:  (Indexes should have been loadded before.)

export ds=50000
export sl=0
export dx=0.01
export dy=0.01
export d_dist=f

. ./run-GenerateQueries    # sometime, . at the beginning makes all exports global in the current shell.
./run-Queries-Dynamic
./run-Queries-Static
./run-compare-results